version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
